
CREATE TABLE CUSTOMER(
    ID int,
    Name varchar(255),
    AMOUNT int,
    Broker_ID int
);

INSERT INTO CUSTOMER
VALUES (1, "sam", 3000, 4);
INSERT INTO CUSTOMER
VALUES (2, "john", 4000, 2);
INSERT INTO CUSTOMER
VALUES (3, "mack", 5000, 2);
INSERT INTO CUSTOMER
VALUES (4, "test", 3000, 3);
INSERT INTO CUSTOMER
VALUES (5, "june", 2000, 3);
INSERT INTO CUSTOMER
VALUES (6, "mike", 4000, 1);
INSERT INTO CUSTOMER
VALUES (7, "annie", 4000, 2);
INSERT INTO CUSTOMER
VALUES (8, "micheal", 2000, 1);
INSERT INTO CUSTOMER
VALUES (9, "tom", 2000, 4);
INSERT INTO CUSTOMER
VALUES (10, "jason", 6000, 4);

CREATE TABLE BROKER(
    ID int,
    Name varchar(255),
);
INSERT INTO BROKER
VALUES (1, Ted);
INSERT INTO BROKER
VALUES (2, Mark);
INSERT INTO BROKER
VALUES (3, Aaron);
INSERT INTO BROKER
VALUES (4, Luke);



SELECT COUNT(CUSTOMER.BROKER_ID) AS NUMBER_OF_CUSTOMERS,BROKER.NAME AS BROKER
FROM CUSTOMER
INNER JOIN BROKER
ON CUSTOMER.BROKER_ID = BROKER.ID
ORDER BY NUMBER_OF_CUSTOMERS DESC, BROKER ASC
